name: Python Tests

on:
  push:
    branches: [feature/transcribing]
  pull_request:
    branches: [feature/transcribing]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create .env file
        run: |
          echo "TRANSCRIBER_HOST=127.0.0.1" >> .env
          echo "TRANSCRIBER_PORT=8070" >> .env

      - name: Run tests
        run: |
          pytest test_websocket_client.py
